# -*- coding: utf-8 -*-
"""Part 1 & 2 : Setup and Install Dependencies.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t8ZEcaU1EW8aLCJjcsF6ib5AxjN3Ol8h
"""

!pip install transformers torchvision torchaudio --quiet
!pip install opencv-python moviepy --quiet

from google.colab import files
drive.mount('/content/drive')

!pip install newspaper3k --upgrade --quiet
!pip install lxml_html_clean --quiet
# Add this at the top of your notebook if not already installed
!pip install instaloader --quiet

from newspaper import Article
from bs4 import BeautifulSoup
import requests
import instaloader
import re
import pandas as pd


def extract_text_from_url(url):
    try:
        if 'youtube.com' in url:
            return "YouTube video title or transcript parsing not implemented."
        elif 'instagram.com' in url:
            shortcode = re.search(r'/p/([^/]+)/', url)
            if shortcode:
                shortcode = shortcode.group(1)
                try:
                    L = instaloader.Instaloader()
                    post = instaloader.Post.from_shortcode(L.context, shortcode)
                    return post.caption if post.caption else ""
                except:
                    try:
                        page = requests.get(url, headers={"User-Agent": "Mozilla/5.0"})
                        soup = BeautifulSoup(page.content, 'html.parser')
                        meta = soup.find('meta', property='og:description')
                        return meta['content'] if meta else ""
                    except:
                        return ""
        else:
            article = Article(url)
            article.download()
            article.parse()
            return article.text
    except:
        return ""

# Append new Instagram links (fake/real examples) manually
new_samples = [
    {"text": "https://www.instagram.com/p/DKi1TU2OXdr/", "image_path": "", "video_path": "", "label": "fake"},
    {"text": "https://www.instagram.com/p/DKfGCciRUGN/", "image_path": "", "video_path": "", "label": "fake"},
    {"text": "https://www.instagram.com/p/DKR8fBnRW9y/", "image_path": "", "video_path": "", "label": "fake"},
    {"text": "https://www.instagram.com/p/CKQzKtGjxu7/", "image_path": "", "video_path": "", "label": "real"}
]
new_df = pd.DataFrame(new_samples)

for i in range(len(new_df)):
    new_df.loc[i, 'text'] = new_df.loc[i, 'text'].strip()
    try:
        extracted = extract_text_from_url(new_df.loc[i, 'text'])
        new_df.loc[i, 'text'] = extracted
    except:
        pass

# Combine with existing dataframe
try:
    df  # Check if df already exists
except NameError:
    df = pd.DataFrame(columns=["text", "image_path", "video_path", "label"])

df = pd.concat([df, new_df], ignore_index=True)

# ✅ Clean missing image and video paths
df['image_path'] = df['image_path'].fillna('')
df['video_path'] = df['video_path'].fillna('')